apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-186614/pipeline:3c36fd0c006acfc2511d424f4b84a310977b562f
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
