apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-186614/pipeline:8169a094471292f5cdebdde21e2eec9e8b13c227
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
